
language: java
script: mvn clean test
jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - morinigodiego21@gmail.com # Colocar el email registrado en GitHub
      - guerreromatias24@gmail.com # Colocar el email registrado en GitHub
    on_success: change # default: change - Avisa cuando hay algun cambio en el proyecto
    on_failure: always # default: always - Avisa siempre que el proceso de build falle en Travis